version: "3"

services:
  php:
    container_name: source-analysis-laravel
    build:
      context: ./php
    working_dir: /var/www
    volumes:
      - ./laravel-src:/var/www
    ports:
      - "6008:8000"
      - "6009:9000"
    tty: true
    depends_on:
      - redis

  redis:
    container_name: source-analysis-laravel-redis
    image: redis:4.0.10
    ports:
      - 6079:6379
